version: '2'

services:
  mqtt:
    image: ansi/mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
    entrypoint: /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
    networks:
        - iot
    volumes:
      - ./etc/mosquitto:/etc/mosquitto:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
      - ./var/lib/mosquitto:/var/lib/mosquitto:rw

  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    networks:
      - iot
    volumes:
      - influxdb:/var/lib/influxdb

  node-red:
    image: jamesbrink/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - node-red:/data
    networks:
      - iot
    links:
      - mqtt
      - influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    networks:
      - iot
    links:
      - influxdb

volumes:
  influxdb:
    driver: local
  node-red:
    driver: local
  
networks:
  iot:
