version: '2'

services:
  mqtt:
    #image: ansi/mosquitto
    build:
      context: docker/mosquitto
    container_name: iot-mosquitto
    ports:
      - 1883:1883
    entrypoint: /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
    networks:
        - iot
    volumes:
      - ./etc/mosquitto:/etc/mosquitto:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
      - ./var/lib/mosquitto:/var/lib/mosquitto:rw
      - iot-mqtt:/mosquitto/data:rw
    restart: always

  influxdb:
    #image: influxdb:alpine
    build:
      context: docker/influxdb
    container_name: iot-influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    networks:
      - iot
    volumes:
      - iot-influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: fg2it/grafana-armhf:v5.0.0
    #image: grafana/grafana:latest
    #build:
    #  context: docker/grafana
    container_name: iot-grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    networks:
      - iot
    volumes:
      - ./etc/grafana:/etc/grafana:rw
      - ./var/lib/grafana:/var/lib/grafana:rw
    links:
      - influxdb
    restart: always

  node-red:
    #image: jamesbrink/node-red:latest
    build:
      context: docker/node-red
    container_name: iot-nodered
    ports:
      - "1880:1880"
    volumes:
      - iot-node-red:/data
    networks:
      - iot
    links:
      - mqtt
      - influxdb

  homeetomqtt:
    #image: xxx:0.0.0
    build:
      context: docker/homeeToMqtt
    container_name: iot-homeetomqtt
    networks:
      - iot
    links:
      - mqtt
      - influxdb

volumes:
  iot-mqtt: 
    driver: local
  iot-influxdb:
    driver: local
  iot-node-red:
    driver: local
  
networks:
  iot:
